version: '3.8'
services:
  bevfusion-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: bevfusion:v1
    container_name: bevfusion-dev
    restart: always
    privileged: true
    runtime: nvidia
    shm_size: "16gb"
    stdin_open: true
    tty: true

    volumes:
      - ./:/workspace:cached
      - /media/jeff/Foxconn/dataset/nuscenes:/workspace/data/nuscenes